package org.example.config;

import jakarta.annotation.PostConstruct;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import lombok.RequiredArgsConstructor;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class AllureEnvironmentWriter {

  private final Environment environment;

  @PostConstruct
  public void writeEnvironmentProperties() {
    Properties properties = gatherProperties();
    savePropertiesToAllureResults(properties);
  }

  private Properties gatherProperties() {
    Properties properties = new Properties();
    properties.setProperty("Spring Profile", getActiveProfile());
    properties.setProperty("Base URL", getBaseUrl());
    return properties;
  }

  private String getActiveProfile() {
    String[] activeProfiles = environment.getActiveProfiles();
    return activeProfiles.length > 0 ? String.join(", ", activeProfiles) : "default";
  }

  private String getBaseUrl() {
    return environment.getProperty("booker.base-url", "unknown");
  }

  private void savePropertiesToAllureResults(Properties properties) {
    File allureResultsDir = new File("build/allure-results");
    if (!allureResultsDir.exists()) {
      allureResultsDir.mkdirs();
    }

    try (FileOutputStream fos =
        new FileOutputStream(new File(allureResultsDir, "environment.properties"))) {
      properties.store(fos, "Allure Environment Properties generated by Spring");
    } catch (IOException e) {
      // Silently ignore to prevent breaking test execution
    }
  }
}
