name: GitHub Action Manual Test Run

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - qa
          - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # setup
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # clean test
      - name: Clean tests result
        run: ./gradlew clean

      # run tests
      - name: Run tests
        continue-on-error: false
        run: env=${{ inputs.environment }} ./gradlew test -PincludeTags=regression

      # allure generate allure report
      - name: Generate allure report
        if: always()
        run: ./gradlew allureReport

      # upload artifact
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
